import { GlobalThemeKey, PaletteWithRoles } from "./theme";
import palette from "./palette";

const paletteWithRoles: Record<GlobalThemeKey, PaletteWithRoles> = {
  light: {
    "--bg-primary": palette.gray.L1,
    "--bg-secondary": palette.gray.L2,
    "--bg-warn": palette.yellow.L2,
    "--bg-danger": palette.red.L2,
    "--button-primary": palette.blue.L4,
    "--button-secondary": palette.gray.L4,
    "--button-warn": palette.yellow.L4,
    "--button-danger": palette.red.L4,
    "--text-primary": palette.gray.L1,
    "--text-secondary": palette.gray.L2,
    "--text-warn": palette.yellow.L6,
    "--text-danger": palette.red.L6,
    "--border-primary": palette.gray.L3,
    "--border-secondary": palette.gray.L4,
    "--border-warn": palette.yellow.L5,
    "--border-danger": palette.red.L5,
    "--icon-primary": palette.blue.L7,
    "--icon-secondary": palette.gray.L5,
    "--icon-warn": palette.yellow.L7,
    "--icon-danger": palette.red.L7,
    "--status-primary": palette.green.L6,
    "--status-secondary": palette.blue.L6,
    "--status-warn": palette.yellow.L6,
    "--status-danger": palette.red.L6,
    "--link-primary": palette.blue.L7,
    "--link-secondary": palette.blue.L5,
    "--link-warn": palette.yellow.L7,
    "--link-danger": palette.red.L7,
    "--shadow-primary": palette.gray.L9,
    "--shadow-secondary": palette.gray.L8,
    "--shadow-warn": palette.yellow.L8,
    "--shadow-danger": palette.red.L8,
  },
  dark: {
    "--bg-primary": palette.gray.L9,
    "--bg-secondary": palette.gray.L8,
    "--bg-warn": palette.yellow.L10,
    "--bg-danger": palette.red.L8,
    "--button-primary": palette.blue.L5,
    "--button-secondary": palette.gray.L4,
    "--button-warn": palette.yellow.L9,
    "--button-danger": palette.red.L9,
    "--text-primary": palette.gray.L2,
    "--text-secondary": palette.gray.L8,
    "--text-warn": palette.yellow.L10,
    "--text-danger": palette.red.L9,
    "--border-primary": palette.gray.L5,
    "--border-secondary": palette.gray.L7,
    "--border-warn": palette.yellow.L9,
    "--border-danger": palette.red.L9,
    "--icon-primary": palette.gray.L6,
    "--icon-secondary": palette.gray.L8,
    "--icon-warn": palette.yellow.L10,
    "--icon-danger": palette.red.L10,
    "--status-primary": palette.green.L9,
    "--status-secondary": palette.blue.L5,
    "--status-warn": palette.yellow.L9,
    "--status-danger": palette.red.L9,
    "--link-primary": palette.blue.L8,
    "--link-secondary": palette.blue.L10,
    "--link-warn": palette.yellow.L10,
    "--link-danger": palette.red.L10,
    "--shadow-primary": palette.blackAlpha.L2,
    "--shadow-secondary": palette.gray.L4,
    "--shadow-warn": palette.yellow.L4,
    "--shadow-danger": palette.red.L4,
  },
};

export default paletteWithRoles;
