import { GlobalThemeKey, PaletteWithRoles } from "./theme";

const paletteWithRoles: Record<GlobalThemeKey, PaletteWithRoles> = {
  light: {
    "--bg-primary": "gray-L10",
    "--bg-secondary": "gray-L1",
    "--bg-warn": "gray-L1",
    "--bg-danger": "gray-L1",
    "--button-primary": "gray-L1",
    "--button-secondary": "gray-L1",
    "--button-warn": "gray-L1",
    "--button-danger": "gray-L1",
    "--text-primary": "gray-L1",
    "--text-secondary": "gray-L1",
    "--text-warn": "gray-L1",
    "--text-danger": "gray-L1",
    "--border-primary": "gray-L1",
    "--border-secondary": "gray-L1",
    "--border-warn": "gray-L1",
    "--border-danger": "gray-L1",
    "--icon-primary": "gray-L1",
    "--icon-secondary": "gray-L1",
    "--icon-warn": "gray-L1",
    "--icon-danger": "gray-L1",
    "--status-primary": "gray-L1",
    "--status-secondary": "gray-L1",
    "--status-warn": "gray-L1",
    "--status-danger": "gray-L1",
    "--link-primary": "gray-L1",
    "--link-secondary": "gray-L1",
    "--link-warn": "gray-L1",
    "--link-danger": "gray-L1",
    "--shadow-primary": "gray-L1",
    "--shadow-secondary": "gray-L1",
    "--shadow-warn": "gray-L1",
    "--shadow-danger": "gray-L1",
  },
  dark: {
    "--bg-primary": "gray-L1",
    "--bg-secondary": "gray-L1",
    "--bg-warn": "gray-L1",
    "--bg-danger": "gray-L1",
    "--button-primary": "gray-L1",
    "--button-secondary": "gray-L1",
    "--button-warn": "gray-L1",
    "--button-danger": "gray-L1",
    "--text-primary": "gray-L1",
    "--text-secondary": "gray-L1",
    "--text-warn": "gray-L1",
    "--text-danger": "gray-L1",
    "--border-primary": "gray-L1",
    "--border-secondary": "gray-L1",
    "--border-warn": "gray-L1",
    "--border-danger": "gray-L1",
    "--icon-primary": "gray-L1",
    "--icon-secondary": "gray-L1",
    "--icon-warn": "gray-L1",
    "--icon-danger": "gray-L1",
    "--status-primary": "gray-L1",
    "--status-secondary": "gray-L1",
    "--status-warn": "gray-L1",
    "--status-danger": "gray-L1",
    "--link-primary": "gray-L1",
    "--link-secondary": "gray-L1",
    "--link-warn": "gray-L1",
    "--link-danger": "gray-L1",
    "--shadow-primary": "gray-L1",
    "--shadow-secondary": "gray-L1",
    "--shadow-warn": "gray-L1",
    "--shadow-danger": "gray-L1",
  },
};

export default paletteWithRoles;